# Generated by Django 4.0.3 on 2022-03-17 17:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='article id')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('created_on', models.DateTimeField(verbose_name='article written on')),
                ('updated_on', models.DateTimeField(verbose_name='article updated on')),
                ('content', models.CharField(max_length=4000, verbose_name='content')),
            ],
        ),
    ]
